export function MethodPage() {
  return <>
    <section className="page-intro"><p className="eyebrow">Data & assumptions</p><h1>Clear about what<br />we know.</h1><p>This prototype explains a possible approach. Its products, prices and environmental values are fictional, and its campaign outcomes are illustrative.</p></section>
    <div className="method-layout"><aside><nav aria-label="On this page"><h2>On this page</h2><a href="#/method?section=sustainability">Sustainability & scope</a><a href="#/method?section=data">The example data</a><a href="#/method?section=model">Campaign model</a><a href="#/method?section=limits">What remains open</a><a href="#/method?section=sources">Sources</a></nav></aside><div>
      <section className="method-section" id="sustainability" tabIndex={-1}>
        <h2>More than a climate figure.</h2>
        <p>We use environmental, social and economic perspectives together. The aim is to help meet a real household need within environmental limits, with a financially workable offer. Higher revenue does not cancel out environmental harm, and a lower product footprint does not guarantee a sustainable campaign.</p>
        <ul className="plain-list">
          <li><strong>Environmental:</strong> the demo accounts for total climate footprint and virgin material use, including additional purchases. It assumes equal product life. Other impacts are not assessed.</li>
          <li><strong>Social:</strong> it checks whether a suitable product fits a stated budget and makes the same offer available to everyone. A pilot could measure how many customers can find a suitable, affordable option and whether they understand the comparison. Affordability alone does not establish social sustainability.</li>
          <li><strong>Economic:</strong> it shows discount allocation and sales revenue. A pilot would also need costs, margins and the purchases that would have happened without the offer. Profit is not calculated here.</li>
        </ul>
        <p>The digital contribution is a shared offer and a clear comparison of assumptions across two views. The prototype stores no customer account or purchase history. A production service would also need data governance, accessible user testing and consideration of its own resource use.</p>
        <p>These are proposed contributions and indicators, not measured improvements. Labour conditions, biodiversity, water use and long-term outcomes remain outside this prototype’s assessment.</p>
      </section>
      <section className="method-section" id="data" tabIndex={-1}><h2>Comparable for this example.</h2><p>Both cabinets are assumed to meet the same storage, load and safety needs, with two adjustable shelves and dimensions of 80 × 40 × 90 cm. Both are assumed to last ten years under equivalent use.</p><p>The customer demo checks the category, maximum width and minimum shelf requirement before showing the pair. It checks budget separately, so a product can fit the practical requirements while remaining above the customer’s budget.</p><p>Climate values represent a synthetic cradle-to-grave footprint for one cabinet over that period. Delivery conditions are assumed equal and already included. Virgin material figures represent material used per cabinet, not its total weight.</p><p>These values are not lifecycle assessments. A real comparison would need verified, consistent system boundaries and evidence of functional equivalence.</p><dl className="spec-list"><div><dt>Original cabinet</dt><dd>899 kr · 40 kg CO₂e · 12 kg virgin material</dd></div><div><dt>Alternative cabinet</dt><dd>999 kr · 25 kg CO₂e · 8 kg virgin material</dd></div><div><dt>Default alternative offer</dt><dd>849 kr · 150 kr product discount</dd></div></dl></section>
      <section className="method-section" id="model" tabIndex={-1}><h2>Count the whole campaign.</h2><p>The baseline assumes 100 starting-option purchases. Each demand scenario assumes 40 starting-option purchases, 60 switches to the alternative, and either 10 or 40 additional purchases of the alternative. These switches are fixed assumptions, even when no discount is selected. They are not a prediction of how different offers will change demand.</p><div className="formula-block"><p><strong>Baseline</strong><br />100 × 40 = 4,000 kg CO₂e</p><p><strong>With 10 additional purchases</strong><br />(40 × 40) + (70 × 25) = 3,350 kg CO₂e</p><p><strong>With 40 additional purchases</strong><br />(40 × 40) + (100 × 25) = 4,100 kg CO₂e</p></div><p>The same unit-count approach is used for virgin material. Demo limits of 3,600 kg CO₂e and 1,080 kg material are 10% below the baseline. They are not IKEA’s corporate targets, and meeting them is not a complete sustainability assessment.</p><p>Discount allocation equals the number of alternative cabinets multiplied by the discount. Revenue equals units multiplied by their final prices. With the default 150 kr discount and moderate demand, 70 × 150 = 10,500 kr is allocated to discounts. This is foregone revenue against the regular price for those assumed units, not a calculated net loss. The 12,000 kr budget is illustrative. Product costs and profit are not modelled.</p></section>
      <section className="method-section" id="limits" tabIndex={-1}><h2>What this does not prove.</h2><p>A selection in the prototype is not a purchase, and a modelled difference is not an observed emissions reduction. We do not know how much of a real campaign would create new demand or replace existing purchases.</p><ul className="plain-list"><li>Compare a pilot with a suitable control to understand purchase substitution.</li><li>Check product durability, returns and real household needs.</li><li>Consider other impacts, including water, biodiversity and labour conditions.</li><li>Track changes across categories and the wider value chain, not only this campaign.</li><li>Validate costs, margins, product data and offer feasibility with relevant stakeholders.</li></ul><p>The current prototype runs in your browser. It has no checkout, live stock, customer accounts or connection to IKEA systems. The offer amount is shared between the two demo views; customer selections and fixed IKEA demand scenarios remain separate. Budget and requirements are held only in browser memory. Refreshing resets the demo.</p></section>
      <section className="method-section" id="sources" tabIndex={-1}><h2>Sources & project references.</h2><ol className="source-list"><li><strong>TEK830 Capstone Project Instructions.</strong><p>Course brief supplied to the team: prototype, project website, user focus, sustainability and presentation requirements.</p></li><li><strong>IKEA Innovation Challenges, 24 August 2026.</strong><p>Challenge 1: sustainable affordability, growth and absolute impact. Emma’s proto-persona is taken from this brief. The supplied document is not redistributed here.</p></li><li><a href="https://medium.com/citrakara-mandala/what-the-heck-is-sustainability-a-brief-look-into-its-origin-and-paradigm-7c9705d5375f">What the Heck is Sustainability? A Brief Look into Its Origin and Paradigm</a><p>Geraldy Kianta, 2020. Background on sustainability and the relationship between environmental, social and economic systems.</p></li><li><strong>Team-created sample dataset.</strong><p>Fictional cabinets, prices, lifecycle assumptions and campaign scenarios. No claims about actual IKEA products or internal pricing practices.</p></li></ol></section>
    </div></div>
  </>
}
