import { Arrow } from '../components/Layout'

export function ProjectPage() {
  return <>
    <section className="page-intro"><p className="eyebrow">TEK830 · Sustainable digitalization</p><h1>Everyday choices.<br />A bigger question.</h1><p>How can IKEA make sustainable choices more affordable while growing within absolute climate and resource limits?</p></section>
    <section className="section split-section"><div><p className="eyebrow">Our focus</p><h2>Challenge 1.<br />Emma comes first.</h2></div><div className="reading-copy"><p>Emma is 32 and planning for a young family. The challenge’s proto-persona describes someone who wants sustainable products and has a limited household budget.</p><p>Prisväxeln explores the price gap between a planned purchase and a comparable alternative. The storage need, product pair and prices are our illustrative design scenario.</p><p>The IKEA view supports the offer. Success for Emma still means finding a suitable product at a price she can afford.</p><a className="text-link" href="#/emma">Walk through her choice <Arrow /></a></div></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">Sustainability in practice</p><h2>Three connected responsibilities.</h2></div><p>Economic value needs to work within social needs and environmental limits.</p></div><div className="steps-grid"><article className="step"><span className="step-number">01</span><h3>Environmental limits</h3><p>Compare total climate and virgin material use, including additional purchases. Lower impact per product is only one part of the question.</p></article><article className="step"><span className="step-number">02</span><h3>Everyday accessibility</h3><p>Make final prices, practical features and choices understandable. The offer is attached to the product, not a personal willingness-to-pay score.</p></article><article className="step"><span className="step-number">03</span><h3>Economic feasibility</h3><p>Show the discount budget and revenue. Real costs and margins would be needed before making a claim about profitability.</p></article></div></section>
    <section className="section split-section"><div><p className="eyebrow">Our process</p><h2>A concept we can<br />put to the test.</h2></div><ol className="process-list"><li><span className="tag">Completed</span><h3>Frame the challenge</h3><p>Review the course brief, focus on Challenge 1 and make Emma’s affordability problem central.</p></li><li><span className="tag">Current stage</span><h3>Make the idea visible</h3><p>Build a first web prototype with a customer comparison and two illustrative campaign scenarios.</p></li><li><span className="tag">Planned</span><h3>Listen and refine</h3><p>Ask users to compare options, explain the offer and identify uncertainties. Record feedback and revise the concept.</p></li><li><span className="tag">Planned</span><h3>Validate and present</h3><p>Discuss feasibility with stakeholders, strengthen the evidence and prepare the final demonstration.</p></li></ol></section>
    <section className="section"><p className="eyebrow">Project materials</p><h2>Follow the work.</h2><div className="materials-list"><article><div><h3>Explore the prototype</h3><p>The customer journey and IKEA campaign perspective.</p></div><a className="text-link" href="#/emma">Open prototype <Arrow /></a></article><article><div><h3>Project pitch</h3><p>A short introduction to the problem and proposed solution.</p></div><span className="tag">Video planned</span></article><article><div><h3>Final presentation</h3><p>Our design decisions, findings and next steps.</p></div><span className="tag">Slides planned</span></article><article><div><h3>Demonstration video</h3><p>A walkthrough of the finished core feature.</p></div><span className="tag">Recording planned</span></article></div></section>
    <section className="section split-section" id="team" tabIndex={-1}><div><p className="eyebrow">The people behind it</p><h2>Four perspectives.<br />One shared project.</h2></div><div className="reading-copy"><p>We are a team of four students working on the TEK830 capstone project at Chalmers.</p><p>Team names, individual contributions and a shared contact address will be added before submission.</p><a className="text-link" href="https://github.com/Nqot/tek830-ikea-prisvaxel">View the project repository <Arrow /></a></div></section>
    <section className="section split-section" id="ai" tabIndex={-1}><div><p className="eyebrow">Transparency</p><h2>How AI supports<br />this work.</h2></div><div className="reading-copy"><p>Generative AI has supported concept exploration, critique, implementation planning, interface copy and frontend code. The product illustrations are original SVG drawings created for this prototype.</p><p>The team is responsible for reviewing the output, checking sources and assumptions, making design decisions and explaining its own contribution. AI-generated examples do not replace stakeholder research or verified product data.</p><a className="text-link" href="#/method">Read our sources and assumptions <Arrow /></a></div></section>
  </>
}
